namespace Arc.Ddsi.BgiDisassembler
{
    internal partial class Disassembler
    {
        private static readonly string[] Mnemonics =
        {
            "push",             // 00
            "push",             // 01
            "push",             // 02,
            null,               // 03,
            "getvarptr",        // 04,
            "getcodeptr",       // 05
            "getcodeoffset",    // 06
            null,               // 07
            "load",             // 08
            "storepv",          // 09 - expects the destination Pointer to be pushed before the Value
            "storevp",          // 0A - expects the Value to be pushed before the destination Pointer
            "write",            // 0B
            "storemulti",       // 0C
            null,               // 0D
            null,               // 0E
            null,               // 0F
            "getsp",            // 10 - get stack pointer
            "setsp",            // 11 - set stack pointer
            null,               // 12
            null,               // 13
            "jmp",              // 14
            "jmp",              // 15
            "call",             // 16
            "ret",              // 17
            null,               // 18
            null,               // 19
            null,               // 1A
            null,               // 1B
            null,               // 1C
            null,               // 1D
            null,               // 1E
            null,               // 1F
            "add",              // 20
            "sub",              // 21
            "mul",              // 22
            "div",              // 23
            "mod",              // 24
            "binand",           // 25
            "binor",            // 26
            "binxor",           // 27
            "binnot",           // 28
            "shl",              // 29
            "shr",              // 2A
            "sar",              // 2B
            null,               // 2C
            null,               // 2D
            null,               // 2E
            null,               // 2F
            "eq",               // 30
            "ne",               // 31
            "le",               // 32
            "ge",               // 33
            "less",             // 34
            "greater",          // 35
            null,               // 36
            null,               // 37
            "logand",           // 38
            "logor",            // 39
            "lognot",           // 3A
            null,               // 3B
            null,               // 3C
            null,               // 3D
            null,               // 3E
            null,               // 3F
            "if",               // 40 - cond?trueval:falseval operator
            null,               // 41
            "muldiv",           // 42
            "arctan",           // 43
            "veclen",           // 44
            null,               // 45
            null,               // 46
            null,               // 47
            "sin",              // 48
            "cos",              // 49
            null,               // 4A
            null,               // 4B
            null,               // 4C
            null,               // 4D
            null,               // 4E
            null,               // 4F
            "add64",            // 50
            "sub64",            // 51
            "mul64",            // 52
            "div64",            // 53
            "mod64",            // 54
            null,               // 55
            null,               // 56
            null,               // 57
            null,               // 58
            null,               // 59
            null,               // 5A
            null,               // 5B
            null,               // 5C
            null,               // 5D
            null,               // 5E
            null,               // 5F
            "memcpy",           // 60
            "memclear",         // 61
            "memset",           // 62
            "memeq",            // 63
            "memcpymulti",      // 64
            "memcmpmulti",      // 65
            "strstr",           // 66
            "strreplace",       // 67
            "strlen",           // 68
            "streq",            // 69
            "strcpy",           // 6A
            "concat",           // 6B
            "getchar",          // 6C
            "tolower",          // 6D
            "quote",            // 6E
            "sprintf",          // 6F
            "malloc",           // 70
            "free",             // 71
            null,               // 72
            null,               // 73
            "enablewritelog",   // 74
            "stralloc",         // 75
            null,               // 76
            "getgamestate",     // 77
            "confirm",          // 78
            "message",          // 79
            "assert",           // 7A
            "dumpmem",          // 7B
            "7C",               // 7C
            "7D",               // 7D
            "setclipboardtext", // 7E
            "7F",               // 7F
            "syscall",          // 80
            "syscall",          // 81
            null,               // 82
            null,               // 83
            null,               // 84
            null,               // 85
            null,               // 86
            null,               // 87
            null,               // 88
            null,               // 89
            null,               // 8A
            null,               // 8B
            null,               // 8C
            null,               // 8D
            null,               // 8E
            null,               // 8F
            "graphcall",        // 90
            "graphcall",        // 91
            "graphcall",        // 92
            null,               // 93
            null,               // 94
            null,               // 95
            null,               // 96
            null,               // 97
            null,               // 98
            null,               // 99
            null,               // 9A
            null,               // 9B
            null,               // 9C
            null,               // 9D
            null,               // 9E
            null,               // 9F
            "soundcall",        // A0
            null,               // A1
            null,               // A2
            null,               // A3
            null,               // A4
            null,               // A5
            null,               // A6
            null,               // A7
            null,               // A8
            null,               // A9
            null,               // AA
            null,               // AB
            null,               // AC
            null,               // AD
            null,               // AE
            null,               // AF
            "extcall",          // B0
            null,               // B1
            null,               // B2
            null,               // B3
            null,               // B4
            null,               // B5
            null,               // B6
            null,               // B7
            null,               // B8
            null,               // B9
            null,               // BA
            null,               // BB
            null,               // BC
            null,               // BD
            null,               // BE
            null,               // BF
            "extcall",          // C0
            null,               // C1
            null,               // C2
            null,               // C3
            null,               // C4
            null,               // C5
            null,               // C6
            null,               // C7
            null,               // C8
            null,               // C9
            null,               // CA
            null,               // CB
            null,               // CC
            null,               // CD
            null,               // CE
            null,               // CF
            null,               // D0
            null,               // D1
            null,               // D2
            null,               // D3
            null,               // D4
            null,               // D5
            null,               // D6
            null,               // D7
            null,               // D8
            null,               // D9
            null,               // DA
            null,               // DB
            null,               // DC
            null,               // DD
            null,               // DE
            null,               // DF
            null,               // E0
            null,               // E1
            null,               // E2
            null,               // E3
            null,               // E4
            null,               // E5
            null,               // E6
            null,               // E7
            null,               // E8
            null,               // E9
            null,               // EA
            null,               // EB
            null,               // EC
            null,               // ED
            null,               // EE
            null,               // EF
            null,               // F0
            null,               // F1
            null,               // F2
            null,               // F3
            null,               // F4
            null,               // F5
            null,               // F6
            null,               // F7
            null,               // F8
            null,               // F9
            null,               // FA
            null,               // FB
            null,               // FC
            null,               // FD
            null,               // FE
            "userscript"        // FF
        };
    }
}
